### ISSUE TITLE
fatal errors while installing

### ISSUE THREAD

**Issue by lwb4** [PRUNER/llvm_archer#3]
I'm about to go try manually installing this thing on https://github.com/pruners/archer but I figured I should post what happened to me anyway.

I just ran `./install.sh --http archer`, and after 7+ hours of downloading/resolving LLVM git stuff, I got this error output:

```
error: unknown type name 'ompt_get_parallel_info_t'; did you mean 'ompt_get_parallel_data_t'?
static ompt_get_parallel_info_t ompt_get_parallel_info;
       ^~~~~~~~~~~~~~~~~~~~~~~~
       ompt_get_parallel_data_t
projects/openmp/runtime/src/ompt.h:413:1: note: 'ompt_get_parallel_data_t' declared here
OMPT_API_FUNCTION(ompt_parallel_data_t, ompt_get_parallel_data, (
^
projects/openmp/runtime/src/ompt.h:394:27: note: expanded from macro 'OMPT_API_FUNCTION'
    typedef return_type (*OMPT_API_FNTYPE(fn)) args
                          ^
projects/openmp/runtime/src/ompt.h:391:29: note: expanded from macro 'OMPT_API_FNTYPE'
#define OMPT_API_FNTYPE(fn) fn##_t
                            ^
<scratch space>:62:1: note: expanded from here
ompt_get_parallel_data_t
^

...

error: statement requires expression of integer type ('ompt_mutex_wait_t' (aka 'void (*)()') invalid)
    switch(kind)
    ^      ~~~~
```

I also got `error: unknown type name 'ompt_scope_endpoint_t'`, `error: unknown type name 'ompt_sync_region_kind_t'`, and a bunch more along those lines (not finding the right methods/data types).

The virtual machine that ran this install script has since restarted and that is all the output I saved.

**Comment by jprotze** [comment]
Thanks for reporting this issue!
Please rerun `./install.sh --http archer` after pulling latest version of the install script.:

```
git pull
./install.sh --http archer
```

This will re-use all downloaded data and built code as possible.

**Comment by lwb4** [comment]
I installed manually on the other repo and deleted the old llvm_archer where I was getting these errors. Thanks for your response, and hopefully this helps the next person! :)
